include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # 自定义规则
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    
    # 导入规则
    always_use_package_imports: false
    prefer_relative_imports: true
    
    # 文档规则
    public_member_api_docs: false
    
    # 其他规则
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_super_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
  
  errors:
    # 将警告提升为错误
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true